apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f test.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ftp
  name: ftp
spec:
  ports:
    - name: "2222"
      port: 2222
      targetPort: 22
  selector:
    io.kompose.service: ftp
status:
  loadBalancer: {}
