apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f test.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ftp
  name: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ftp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f test.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ftp
    spec:
      containers:
        - args:
            - foo:pass:1001
          image: atmoz/sftp
          name: ftp
          ports:
            - containerPort: 22
          resources: {}
          volumeMounts:
            - mountPath: /home/foo/upload
              name: ftp-claim0
      restartPolicy: Always
      volumes:
        - name: ftp-claim0
          persistentVolumeClaim:
            claimName: ftp-claim0
status: {}
